lenguage: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  app: encurtador-wiser
  skip_cleanup: true
  api_key:
    secure: EBSDC6KPu1URE5gvLdvhN9R4Nzm+kF/t5n5Aj+lWZcOlofj7F69vQlUefOLmJcaSxoPYndAuHJ09gssuSNO375hcwmzx0JcpsBR/zEKsSjtIVOCbPbZlq+0dQC7xDjhxMNtNhBQbl/R0CByxP5Vg82yRzW9c1t3W1ks3f1HLro1IlJLO9I4WN7qTS7PKDUGzL/J/9lf9j/WA3mrI+DKec21T2/rfRuVt1WiXuxGGxUMqkvUUBiqqj8vPZCRpEW/XNOG7vZ34k2Vb1+4zZ+cdOUWJ1etbNrygoyg4WvWK1XafQ8M4ooCapHmzb9tzW4c/6lo7jXKwv9hRoEoUGR5BdWAXvZTon3vyrTT+MYeWeyyKxWRkBApAAaVNVi2mtWJsw86DfMCNgRpBizcJV1W9myCes9Xwu+uUIhncxOZF+JMVAU3Tdwasa1gW5k2AouZV6+e+texsBE7F2KJExfXtxnUPBb19yNW1m1RcRyudhsTj6iXIx2fbSQL++5F4AGKuUmHwl4OzXUiwvvuuSHQG/vhNXcDOq6QxQdLPSobwhpcmId3liRavjt+cZqXg/6hAlLQ+4ggTI6ZWpiF1RqawMPl1yEIy+ytfbFlVcQCmF0AY8RHvLWQoQQpw0pxLpnMBsfFhOR6LkVD0VEgshwGTby77YQu1O72gRMDXLdssxzw=
