lenguage: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: R5+AF/mw0YZMrbMDmIXBVOD5OVP4rf3o95WfJjtq96c/JE/JekxKMMPSd8m0hnIdEbZVZcrObhJ3BI+OnDD9INY5Mlu9vrauY6RjFRZM0+BrEHVRkGfJu+qHpzP56dTcii63CjdG0X0QbjBK6Wp5oJUf23tHch4oR2T985fD+3IiK3QeTMBbTpOjiGHcD79uspdKoWpg5BwTb867PQvPZvY0FF5SeH4jInwUQMKTvN6jKJd65gvi1Dszqfaa7Pyl4gKAV2J2BjYR0JtD2jfyg7KRQAxQLOrUX69maKsQfyrtTnK2pcADowSEUQ+iwCoZcZ3YWhRDNZIull/7pxSq/zz9e436DCVb7EsHmMLMXmOOEuL0bAx7ne+ECIoUHn4ey+tG30BS7Cs0iIwVhMRnXfAV30+6qDOk8RZFsKt0cttOuHZz9Ut9/ZEu2rPL3cNHNxjtXMJBJr9N9Dk1bwMKWndnVUdEaNEPs9SBM+rmcB6ALvD2G3sX0HmXfXCIC+YDfaxsnXr//1YLAhxlUBxU3fTsYdIo7brWwZqpFrNqRS9hZptsJr6JpIKh+tKWLIY29d4Ml6yj1NI78oICMUwY+vhAXAnpTAYnmuLf8ftR8zFdxJuxKLsvzGVsYr4VjeDjbTdSRh1tGhm4YWDCEs203V9IAHySjbSgXq3UWIK5vyY=
